/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicios;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       E24p classUnderTest = newE24p();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
