/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio20;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Exercicio20p classUnderTest = newExercicio20p();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
